-- VHDL Entity ece411.Cache_L1.symbol
--
-- Created:
--          by - ece411.ece411 (localhost)
--          at - 02:23:55 12/09/12
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2005.3 (Build 75)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

LIBRARY ece411;
USE ece411.LC3B_TYPES.all;
USE ieee.NUMERIC_STD.all;

ENTITY Cache_L1 IS
   PORT( 
      ADDRESS   : IN     LC3b_word;
      DATAOUT   : IN     LC3b_word;
      MREAD_L   : IN     std_logic;
      MWRITEH_L : IN     std_logic;
      MWRITEL_L : IN     std_logic;
      clk       : IN     std_logic;
      pmdatain  : IN     LC3b_Oword;
      pmresp_h  : IN     std_logic;
      reset_l   : IN     std_logic;
      DATAIN    : OUT    LC3b_word;
      MRESP_H   : OUT    std_logic;
      pmaddress : OUT    LC3b_word;
      pmdataout : OUT    LC3b_Oword;
      pmread_l  : OUT    std_logic;
      pmwrite_l : OUT    std_logic
   );

-- Declarations

END Cache_L1 ;

--
-- VHDL Architecture ece411.Cache_L1.struct
--
-- Created:
--          by - ece411.ece411 (localhost)
--          at - 02:23:56 12/09/12
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2005.3 (Build 75)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

LIBRARY ece411;
USE ece411.LC3B_TYPES.all;
USE ieee.NUMERIC_STD.all;

LIBRARY ece411;

ARCHITECTURE struct OF Cache_L1 IS

   -- Architecture declarations

   -- Internal signal declarations
   SIGNAL DataMuxSel   : std_logic;
   SIGNAL Dirty        : std_logic;
   SIGNAL LRU_Dirty    : std_logic;
   SIGNAL MISS_H       : std_logic;
   SIGNAL Resp_en      : std_logic;
   SIGNAL Valid        : std_logic;
   SIGNAL WBAddrMuxSel : std_logic;
   SIGNAL WriteLine_h  : std_logic;
   SIGNAL WriteValid_h : std_logic;


   -- Component Declarations
   COMPONENT L1_Controller
   PORT (
      LRU_Dirty    : IN     std_logic ;
      MISS_H       : IN     std_logic ;
      clk          : IN     std_logic ;
      pmresp_h     : IN     std_logic ;
      reset_l      : IN     std_logic ;
      DataMuxSel   : OUT    std_logic ;
      Dirty        : OUT    std_logic ;
      Resp_en      : OUT    std_logic ;
      Valid        : OUT    std_logic ;
      WBAddrMuxSel : OUT    std_logic ;
      WriteLine_h  : OUT    std_logic ;
      WriteValid_h : OUT    std_logic ;
      pmread_l     : OUT    std_logic ;
      pmwrite_l    : OUT    std_logic 
   );
   END COMPONENT;
   COMPONENT L1_Datapath
   PORT (
      ADDRESS      : IN     LC3b_word ;
      DATAOUT      : IN     LC3b_word ;
      DataMuxSel   : IN     std_logic ;
      Dirty        : IN     std_logic ;
      MREAD_L      : IN     std_logic ;
      MWRITEH_L    : IN     std_logic ;
      MWRITEL_L    : IN     std_logic ;
      Resp_en      : IN     std_logic ;
      Valid        : IN     std_logic ;
      WBAddrMuxSel : IN     std_logic ;
      WriteLine_h  : IN     std_logic ;
      WriteValid_h : IN     std_logic ;
      clk          : IN     std_logic ;
      pmdatain     : IN     LC3b_Oword ;
      pmresp_h     : IN     std_logic ;
      reset_l      : IN     std_logic ;
      DATAIN       : OUT    LC3b_word ;
      LRU_Dirty    : OUT    std_logic ;
      MISS_H       : OUT    std_logic ;
      MRESP_H      : OUT    std_logic ;
      pmaddress    : OUT    LC3b_word ;
      pmdataout    : OUT    LC3b_Oword 
   );
   END COMPONENT;

   -- Optional embedded configurations
   -- pragma synthesis_off
   FOR ALL : L1_Controller USE ENTITY ece411.L1_Controller;
   FOR ALL : L1_Datapath USE ENTITY ece411.L1_Datapath;
   -- pragma synthesis_on


BEGIN

   -- Instance port mappings.
   Controller : L1_Controller
      PORT MAP (
         LRU_Dirty    => LRU_Dirty,
         MISS_H       => MISS_H,
         clk          => clk,
         pmresp_h     => pmresp_h,
         reset_l      => reset_l,
         DataMuxSel   => DataMuxSel,
         Dirty        => Dirty,
         Resp_en      => Resp_en,
         Valid        => Valid,
         WBAddrMuxSel => WBAddrMuxSel,
         WriteLine_h  => WriteLine_h,
         WriteValid_h => WriteValid_h,
         pmread_l     => pmread_l,
         pmwrite_l    => pmwrite_l
      );
   Datapath : L1_Datapath
      PORT MAP (
         ADDRESS      => ADDRESS,
         DATAOUT      => DATAOUT,
         DataMuxSel   => DataMuxSel,
         Dirty        => Dirty,
         MREAD_L      => MREAD_L,
         MWRITEH_L    => MWRITEH_L,
         MWRITEL_L    => MWRITEL_L,
         Resp_en      => Resp_en,
         Valid        => Valid,
         WBAddrMuxSel => WBAddrMuxSel,
         WriteLine_h  => WriteLine_h,
         WriteValid_h => WriteValid_h,
         clk          => clk,
         pmdatain     => pmdatain,
         pmresp_h     => pmresp_h,
         reset_l      => reset_l,
         DATAIN       => DATAIN,
         LRU_Dirty    => LRU_Dirty,
         MISS_H       => MISS_H,
         MRESP_H      => MRESP_H,
         pmaddress    => pmaddress,
         pmdataout    => pmdataout
      );

END struct;
