-- VHDL Entity ece411.encoder_8to3.symbol
--
-- Created:
--          by - ece411.ece411 (localhost)
--          at - 02:23:58 12/09/12
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2005.3 (Build 75)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.NUMERIC_STD.all;

LIBRARY ece411;
USE ece411.LC3b_types.all;

ENTITY encoder_8to3 IS
   PORT( 
      I0     : IN     std_logic;
      I1     : IN     std_logic;
      I2     : IN     std_logic;
      I3     : IN     std_logic;
      I4     : IN     std_logic;
      I5     : IN     std_logic;
      I6     : IN     std_logic;
      I7     : IN     std_logic;
      output : OUT    LC3b_8mux_sel
   );

-- Declarations

END encoder_8to3 ;

--
-- VHDL Architecture ece411.encoder_8to3.struct
--
-- Created:
--          by - ece411.ece411 (localhost)
--          at - 02:23:58 12/09/12
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2005.3 (Build 75)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.NUMERIC_STD.all;

LIBRARY ece411;
USE ece411.LC3b_types.all;

LIBRARY ece411;

ARCHITECTURE struct OF encoder_8to3 IS

   -- Architecture declarations

   -- Internal signal declarations
   SIGNAL bit0 : std_logic;
   SIGNAL bit1 : std_logic;
   SIGNAL bit2 : std_logic;


   -- Component Declarations
   COMPONENT BitOR4
   PORT (
      I0 : IN     std_logic ;
      I1 : IN     std_logic ;
      I2 : IN     std_logic ;
      I3 : IN     std_logic ;
      O  : OUT    std_logic 
   );
   END COMPONENT;
   COMPONENT cat3b
   PORT (
      b1  : IN     std_logic ;
      b0  : IN     std_logic ;
      b2  : IN     std_logic ;
      c3b : OUT    LC3b_8mux_sel 
   );
   END COMPONENT;

   -- Optional embedded configurations
   -- pragma synthesis_off
   FOR ALL : BitOR4 USE ENTITY ece411.BitOR4;
   FOR ALL : cat3b USE ENTITY ece411.cat3b;
   -- pragma synthesis_on


BEGIN

   -- Instance port mappings.
   bit0OR : BitOR4
      PORT MAP (
         I0 => I1,
         I1 => I3,
         I2 => I5,
         I3 => I7,
         O  => bit0
      );
   bit1OR : BitOR4
      PORT MAP (
         I0 => I2,
         I1 => I3,
         I2 => I6,
         I3 => I7,
         O  => bit1
      );
   bit3OR : BitOR4
      PORT MAP (
         I0 => I4,
         I1 => I5,
         I2 => I6,
         I3 => I7,
         O  => bit2
      );
   U_0 : cat3b
      PORT MAP (
         b1  => bit1,
         b0  => bit0,
         b2  => bit2,
         c3b => output
      );

END struct;
