-- VHDL Entity ece411.encoder_2to1.symbol
--
-- Created:
--          by - ece411.ece411 (localhost)
--          at - 16:04:57 12/08/12
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2005.3 (Build 75)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.NUMERIC_STD.all;

LIBRARY ece411;
USE ece411.LC3b_types.all;

ENTITY encoder_2to1 IS
   PORT( 
      I0 : IN     std_logic;
      I1 : IN     std_logic;
      O  : OUT    std_logic
   );

-- Declarations

END encoder_2to1 ;

--
-- VHDL Architecture ece411.encoder_2to1.struct
--
-- Created:
--          by - ece411.ece411 (localhost)
--          at - 16:04:57 12/08/12
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2005.3 (Build 75)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.NUMERIC_STD.all;

LIBRARY ece411;
USE ece411.LC3b_types.all;


ARCHITECTURE struct OF encoder_2to1 IS

   -- Architecture declarations

   -- Internal signal declarations



BEGIN
   -- Architecture concurrent statements
   -- HDL Embedded Text Block 1 eb1
   -- encoder output is I1
   O <= I1;              


   -- Instance port mappings.

END struct;
