-- VHDL Entity ece411.IWRegSplitter.symbol
--
-- Created:
--          by - ece411.ece411 (localhost)
--          at - 02:23:56 12/09/12
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2005.3 (Build 75)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.NUMERIC_STD.all;

LIBRARY ece411;
USE ece411.LC3b_types.all;

ENTITY IWRegSplitter IS
   PORT( 
      Dest       : IN     LC3b_reg;
      DestMuxSel : IN     std_logic;
      SrcA       : IN     LC3b_reg;
      SrcB       : IN     LC3b_reg;
      isST       : IN     std_logic;
      noSrcA     : IN     std_logic;
      useSrcB    : IN     std_logic;
      DR         : OUT    LC3b_reg;
      SR1        : OUT    LC3b_reg;
      SR2        : OUT    LC3b_reg
   );

-- Declarations

END IWRegSplitter ;

--
-- VHDL Architecture ece411.IWRegSplitter.struct
--
-- Created:
--          by - ece411.ece411 (localhost)
--          at - 02:23:56 12/09/12
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2005.3 (Build 75)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.NUMERIC_STD.all;

LIBRARY ece411;
USE ece411.LC3b_types.all;

LIBRARY ece411;

ARCHITECTURE struct OF IWRegSplitter IS

   -- Architecture declarations

   -- Internal signal declarations
   SIGNAL SR1MuxSelout : LC3b_4mux_sel;
   SIGNAL SR2MuxSelout : LC3b_4mux_sel;
   SIGNAL reg7         : LC3b_reg;
   SIGNAL x3out        : LC3b_reg;


   -- Component Declarations
   COMPONENT RegMux2
   PORT (
      Sel : IN     std_logic ;
      A   : IN     LC3b_reg ;
      B   : IN     LC3b_reg ;
      F   : OUT    LC3b_reg 
   );
   END COMPONENT;
   COMPONENT RegMux4
   PORT (
      Sel : IN     LC3b_4mux_sel ;
      I0  : IN     LC3b_reg ;
      I1  : IN     LC3b_reg ;
      I2  : IN     LC3b_reg ;
      I3  : IN     LC3b_reg ;
      O   : OUT    LC3b_reg 
   );
   END COMPONENT;
   COMPONENT X3b
   PORT (
      x3out : OUT    LC3b_reg 
   );
   END COMPONENT;
   COMPONENT cat2b
   PORT (
      b1  : IN     std_logic ;
      b0  : IN     std_logic ;
      c2b : OUT    LC3b_4mux_sel 
   );
   END COMPONENT;
   COMPONENT gen7
   PORT (
      reg7 : OUT    LC3b_reg 
   );
   END COMPONENT;

   -- Optional embedded configurations
   -- pragma synthesis_off
   FOR ALL : RegMux2 USE ENTITY ece411.RegMux2;
   FOR ALL : RegMux4 USE ENTITY ece411.RegMux4;
   FOR ALL : X3b USE ENTITY ece411.X3b;
   FOR ALL : cat2b USE ENTITY ece411.cat2b;
   FOR ALL : gen7 USE ENTITY ece411.gen7;
   -- pragma synthesis_on


BEGIN

   -- Instance port mappings.
   DestMux : RegMux2
      PORT MAP (
         Sel => DestMuxSel,
         A   => Dest,
         B   => reg7,
         F   => DR
      );
   SR1Mux : RegMux4
      PORT MAP (
         Sel => SR1MuxSelout,
         I0  => SrcA,
         I1  => Dest,
         I2  => x3out,
         I3  => x3out,
         O   => SR1
      );
   SR2Mux : RegMux4
      PORT MAP (
         Sel => SR2MuxSelout,
         I0  => x3out,
         I1  => SrcB,
         I2  => SrcA,
         I3  => SrcA,
         O   => SR2
      );
   theX3b : X3b
      PORT MAP (
         x3out => x3out
      );
   SR1MuxSel : cat2b
      PORT MAP (
         b1  => noSrcA,
         b0  => isST,
         c2b => SR1MuxSelout
      );
   SR2MuxSel : cat2b
      PORT MAP (
         b1  => isST,
         b0  => useSrcB,
         c2b => SR2MuxSelout
      );
   agen7 : gen7
      PORT MAP (
         reg7 => reg7
      );

END struct;
