-- VHDL Entity ece411.L2_Way.symbol
--
-- Created:
--          by - ece411.ece411 (localhost)
--          at - 02:23:59 12/09/12
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2005.3 (Build 75)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.NUMERIC_STD.all;

LIBRARY ece411;
USE ece411.LC3b_types.all;

ENTITY L2_Way IS
   PORT( 
      dataIn   : IN     LC3b_oword;
      dirtyIn  : IN     std_logic;
      index    : IN     LC3b_c_index;
      reset_l  : IN     std_logic;
      tag      : IN     LC3b_c_tag;
      validIn  : IN     std_logic;
      write    : IN     std_logic;
      writeV   : IN     std_logic;
      dataOut  : OUT    LC3b_Oword;
      dirtyOut : OUT    std_logic;
      hit      : OUT    std_logic;
      tagOut   : OUT    LC3b_c_tag
   );

-- Declarations

END L2_Way ;

--
-- VHDL Architecture ece411.L2_Way.struct
--
-- Created:
--          by - ece411.ece411 (localhost)
--          at - 02:23:59 12/09/12
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2005.3 (Build 75)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.NUMERIC_STD.all;

LIBRARY ece411;
USE ece411.LC3b_types.all;

LIBRARY ece411;

ARCHITECTURE struct OF L2_Way IS

   -- Architecture declarations

   -- Internal signal declarations
   SIGNAL dirtypre : std_logic;
   SIGNAL tagMatch : std_logic;
   SIGNAL validOut : std_logic;

   -- Implicit buffer signal declarations
   SIGNAL tagOut_internal : LC3b_c_tag;


   -- Component Declarations
   COMPONENT BitAND2
   PORT (
      I0 : IN     std_logic ;
      I1 : IN     std_logic ;
      O  : OUT    std_logic 
   );
   END COMPONENT;
   COMPONENT Comp9
   PORT (
      In1 : IN     LC3b_c_tag ;
      In2 : IN     LC3b_c_tag ;
      eq  : OUT    std_logic 
   );
   END COMPONENT;
   COMPONENT L2_TagArray
   PORT (
      reset_l : IN     std_logic ;
      write   : IN     std_logic ;
      index   : IN     LC3b_c_index ;
      tagIn   : IN     LC3b_c_tag ;
      tagOut  : OUT    LC3b_c_tag 
   );
   END COMPONENT;
   COMPONENT L2_bitArray
   PORT (
      reset_l : IN     std_logic ;
      write   : IN     std_logic ;
      index   : IN     LC3b_c_index ;
      bitIn   : IN     std_logic ;
      bitOut  : OUT    std_logic 
   );
   END COMPONENT;
   COMPONENT L2_dataArray
   PORT (
      reset_l : IN     std_logic ;
      write   : IN     std_logic ;
      index   : IN     LC3b_c_index ;
      dataIn  : IN     LC3b_Oword ;
      dataOut : OUT    LC3b_Oword 
   );
   END COMPONENT;

   -- Optional embedded configurations
   -- pragma synthesis_off
   FOR ALL : BitAND2 USE ENTITY ece411.BitAND2;
   FOR ALL : Comp9 USE ENTITY ece411.Comp9;
   FOR ALL : L2_TagArray USE ENTITY ece411.L2_TagArray;
   FOR ALL : L2_bitArray USE ENTITY ece411.L2_bitArray;
   FOR ALL : L2_dataArray USE ENTITY ece411.L2_dataArray;
   -- pragma synthesis_on


BEGIN

   -- Instance port mappings.
   dirtyAND : BitAND2
      PORT MAP (
         I0 => validOut,
         I1 => dirtypre,
         O  => dirtyOut
      );
   hitAND : BitAND2
      PORT MAP (
         I0 => validOut,
         I1 => tagMatch,
         O  => hit
      );
   compTag : Comp9
      PORT MAP (
         In1 => tagOut_internal,
         In2 => tag,
         eq  => tagMatch
      );
   tagArray : L2_TagArray
      PORT MAP (
         reset_l => reset_l,
         write   => write,
         index   => index,
         tagIn   => tag,
         tagOut  => tagOut_internal
      );
   dirtyArray : L2_bitArray
      PORT MAP (
         reset_l => reset_l,
         write   => write,
         index   => index,
         bitIn   => dirtyIn,
         bitOut  => dirtypre
      );
   validArray : L2_bitArray
      PORT MAP (
         reset_l => reset_l,
         write   => writeV,
         index   => index,
         bitIn   => validIn,
         bitOut  => validOut
      );
   dataArray : L2_dataArray
      PORT MAP (
         reset_l => reset_l,
         write   => write,
         index   => index,
         dataIn  => dataIn,
         dataOut => dataOut
      );

   -- Implicit buffered output assignments
   tagOut <= tagOut_internal;

END struct;
