-- VHDL Entity ece411.SRLatch.symbol
--
-- Created:
--          by - ece411.ece411 (localhost)
--          at - 02:07:18 09/26/12
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2005.3 (Build 75)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.NUMERIC_STD.all;

LIBRARY ece411;
USE ece411.LC3b_types.all;

ENTITY SRLatch IS
   PORT( 
      R  : IN     std_logic;
      S  : IN     std_logic;
      Q  : OUT    std_logic;
      nQ : OUT    std_logic
   );

-- Declarations

END SRLatch ;

--
-- VHDL Architecture ece411.SRLatch.struct
--
-- Created:
--          by - ece411.ece411 (localhost)
--          at - 02:07:18 09/26/12
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2005.3 (Build 75)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.NUMERIC_STD.all;

LIBRARY ece411;
USE ece411.LC3b_types.all;

LIBRARY ece411;

ARCHITECTURE struct OF SRLatch IS

   -- Architecture declarations

   -- Internal signal declarations

   -- Implicit buffer signal declarations
   SIGNAL Q_internal  : std_logic;
   SIGNAL nQ_internal : std_logic;


   -- Component Declarations
   COMPONENT BitNOR2
   PORT (
      I0 : IN     std_logic ;
      I1 : IN     std_logic ;
      O  : OUT    std_logic 
   );
   END COMPONENT;

   -- Optional embedded configurations
   -- pragma synthesis_off
   FOR ALL : BitNOR2 USE ENTITY ece411.BitNOR2;
   -- pragma synthesis_on


BEGIN

   -- Instance port mappings.
   U_0 : BitNOR2
      PORT MAP (
         I0 => R,
         I1 => nQ_internal,
         O  => Q_internal
      );
   U_1 : BitNOR2
      PORT MAP (
         I0 => Q_internal,
         I1 => S,
         O  => nQ_internal
      );

   -- Implicit buffered output assignments
   Q  <= Q_internal;
   nQ <= nQ_internal;

END struct;
