-- VHDL Entity ece411.STAGE_FETCH.symbol
--
-- Created:
--          by - ece411.ece411 (localhost)
--          at - 02:23:57 12/09/12
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2005.3 (Build 75)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.NUMERIC_STD.all;

LIBRARY ece411;
USE ece411.LC3b_types.all;

ENTITY STAGE_FETCH IS
   PORT( 
      ExtPC             : IN     LC3b_word;
      PCMuxSel          : IN     std_logic;
      PCTargetin        : IN     LC3b_word;
      WBPCindex         : IN     LC3b_word;
      clk               : IN     std_logic;
      isUnconditionalIn : IN     std_logic;
      loadBTB           : IN     std_logic;
      loadPC            : IN     std_logic;
      mispredict_l      : IN     std_logic;
      predictionIn      : IN     std_logic;
      reset_l           : IN     std_logic;
      PCPlus2out        : OUT    LC3b_word;
      PCTargetout       : OUT    LC3b_word;
      PCout             : OUT    LC3b_word;
      hit               : OUT    std_logic;
      predictionout     : OUT    std_logic
   );

-- Declarations

END STAGE_FETCH ;

--
-- VHDL Architecture ece411.STAGE_FETCH.struct
--
-- Created:
--          by - ece411.ece411 (localhost)
--          at - 02:23:57 12/09/12
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2005.3 (Build 75)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.NUMERIC_STD.all;

LIBRARY ece411;
USE ece411.LC3b_types.all;

LIBRARY ece411;
LIBRARY mp3lib;

ARCHITECTURE struct OF STAGE_FETCH IS

   -- Architecture declarations

   -- Internal signal declarations
   SIGNAL CatPCMuxSel        : LC3b_4mux_sel;
   SIGNAL PCin               : LC3b_word;
   SIGNAL isUnconditionalout : std_logic;
   SIGNAL miss               : std_logic;
   SIGNAL predictedTaken     : STD_LOGIC;
   SIGNAL useBTBPC           : STD_LOGIC;

   -- Implicit buffer signal declarations
   SIGNAL PCout_internal         : LC3b_word;
   SIGNAL PCPlus2out_internal    : LC3b_word;
   SIGNAL hit_internal           : std_logic;
   SIGNAL predictionout_internal : std_logic;
   SIGNAL PCTargetout_internal   : LC3b_word;


   -- Component Declarations
   COMPONENT BTB
   PORT (
      IFPCindex          : IN     LC3b_word ;
      PCTargetin         : IN     LC3b_word ;
      RESET_L            : IN     std_logic ;
      WBPCindex          : IN     LC3b_word ;
      isUnconditionalIn  : IN     std_logic ;
      loadBTB            : IN     std_logic ;
      predictionIn       : IN     std_logic ;
      PCTargetout        : OUT    LC3b_word ;
      hit                : OUT    std_logic ;
      isUnconditionalout : OUT    std_logic ;
      miss               : OUT    std_logic ;
      predictionout      : OUT    std_logic 
   );
   END COMPONENT;
   COMPONENT BitAND3
   PORT (
      I0 : IN     std_logic ;
      I1 : IN     std_logic ;
      I2 : IN     std_logic ;
      O  : OUT    std_logic 
   );
   END COMPONENT;
   COMPONENT Plus2
   PORT (
      Input : IN     LC3b_word ;
      Plus2 : OUT    LC3b_word 
   );
   END COMPONENT;
   COMPONENT Reg16
   PORT (
      reset_l : IN     STD_LOGIC ;
      clk     : IN     STD_LOGIC ;
      en      : IN     STD_LOGIC ;
      input   : IN     LC3b_word ;
      output  : OUT    LC3b_word 
   );
   END COMPONENT;
   COMPONENT WordMux4
   PORT (
      A   : IN     LC3b_word ;
      B   : IN     LC3b_word ;
      C   : IN     LC3b_word ;
      D   : IN     LC3b_word ;
      Sel : IN     LC3b_4mux_sel ;
      F   : OUT    LC3b_word 
   );
   END COMPONENT;
   COMPONENT cat2b
   PORT (
      b1  : IN     std_logic ;
      b0  : IN     std_logic ;
      c2b : OUT    LC3b_4mux_sel 
   );
   END COMPONENT;
   COMPONENT OR2
   PORT (
      A : IN     STD_LOGIC ;
      B : IN     STD_LOGIC ;
      F : OUT    STD_LOGIC 
   );
   END COMPONENT;

   -- Optional embedded configurations
   -- pragma synthesis_off
   FOR ALL : BTB USE ENTITY ece411.BTB;
   FOR ALL : BitAND3 USE ENTITY ece411.BitAND3;
   FOR ALL : OR2 USE ENTITY mp3lib.OR2;
   FOR ALL : Plus2 USE ENTITY ece411.Plus2;
   FOR ALL : Reg16 USE ENTITY ece411.Reg16;
   FOR ALL : WordMux4 USE ENTITY ece411.WordMux4;
   FOR ALL : cat2b USE ENTITY ece411.cat2b;
   -- pragma synthesis_on


BEGIN

   -- Instance port mappings.
   theBTB : BTB
      PORT MAP (
         IFPCindex          => PCout_internal,
         PCTargetin         => PCTargetin,
         RESET_L            => reset_l,
         WBPCindex          => WBPCindex,
         isUnconditionalIn  => isUnconditionalIn,
         loadBTB            => loadBTB,
         predictionIn       => predictionIn,
         PCTargetout        => PCTargetout_internal,
         hit                => hit_internal,
         isUnconditionalout => isUnconditionalout,
         miss               => miss,
         predictionout      => predictionout_internal
      );
   BTBSelAND : BitAND3
      PORT MAP (
         I0 => predictedTaken,
         I1 => hit_internal,
         I2 => mispredict_l,
         O  => useBTBPC
      );
   PCPlus2 : Plus2
      PORT MAP (
         Input => PCout_internal,
         Plus2 => PCPlus2out_internal
      );
   PC : Reg16
      PORT MAP (
         reset_l => reset_l,
         clk     => clk,
         en      => loadPC,
         input   => PCin,
         output  => PCout_internal
      );
   PCMux : WordMux4
      PORT MAP (
         A   => PCPlus2out_internal,
         B   => ExtPC,
         C   => PCTargetout_internal,
         D   => PCTargetout_internal,
         Sel => CatPCMuxSel,
         F   => PCin
      );
   PCMuxSelCat : cat2b
      PORT MAP (
         b1  => useBTBPC,
         b0  => PCMuxSel,
         c2b => CatPCMuxSel
      );
   BTBSelOR : OR2
      PORT MAP (
         A => predictionout_internal,
         B => isUnconditionalout,
         F => predictedTaken
      );

   -- Implicit buffered output assignments
   PCout         <= PCout_internal;
   PCPlus2out    <= PCPlus2out_internal;
   hit           <= hit_internal;
   predictionout <= predictionout_internal;
   PCTargetout   <= PCTargetout_internal;

END struct;
