-- VHDL Entity ece411.StallUnit.symbol
--
-- Created:
--          by - ece411.ece411 (localhost)
--          at - 02:23:56 12/09/12
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2005.3 (Build 75)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

LIBRARY ece411;
USE ece411.LC3B_TYPES.all;
USE ieee.NUMERIC_STD.all;

ENTITY StallUnit IS
   PORT( 
      MREAD_L   : IN     STD_LOGIC;
      MRESP_H   : IN     std_logic;
      MWRITEH_L : IN     STD_LOGIC;
      MWRITEL_L : IN     STD_LOGIC;
      Load      : OUT    std_logic
   );

-- Declarations

END StallUnit ;

--
-- VHDL Architecture ece411.StallUnit.struct
--
-- Created:
--          by - ece411.ece411 (localhost)
--          at - 02:23:56 12/09/12
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2005.3 (Build 75)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

LIBRARY ece411;
USE ece411.LC3B_TYPES.all;
USE ieee.NUMERIC_STD.all;

LIBRARY ece411;
LIBRARY mp3lib;

ARCHITECTURE struct OF StallUnit IS

   -- Architecture declarations

   -- Internal signal declarations
   SIGNAL MConds : STD_LOGIC;


   -- Component Declarations
   COMPONENT BitOR2
   PORT (
      I0 : IN     std_logic ;
      I1 : IN     std_logic ;
      O  : OUT    std_logic 
   );
   END COMPONENT;
   COMPONENT AND3
   PORT (
      A : IN     STD_LOGIC ;
      B : IN     STD_LOGIC ;
      C : IN     STD_LOGIC ;
      F : OUT    STD_LOGIC 
   );
   END COMPONENT;

   -- Optional embedded configurations
   -- pragma synthesis_off
   FOR ALL : AND3 USE ENTITY mp3lib.AND3;
   FOR ALL : BitOR2 USE ENTITY ece411.BitOR2;
   -- pragma synthesis_on


BEGIN

   -- Instance port mappings.
   MRESPOR : BitOR2
      PORT MAP (
         I0 => MRESP_H,
         I1 => MConds,
         O  => Load
      );
   MemCondsAND : AND3
      PORT MAP (
         A => MREAD_L,
         B => MWRITEL_L,
         C => MWRITEH_L,
         F => MConds
      );

END struct;
