echo "--- Executing initialization force file for ../testcode/mp3/catchemall.asm ---"

echo "Resetting processor for 5 ns."
force /reset_l 0 @0
force /reset_l 1 @5

echo "Done initializing processor, loading ../testcode/mp3/catchemall.asm program code."
run 5
change /mp3_cpu/DRAM/vhdl_memory/mem(0) X"24"
change /mp3_cpu/DRAM/vhdl_memory/mem(1) X"1A"
change /mp3_cpu/DRAM/vhdl_memory/mem(2) X"08"
change /mp3_cpu/DRAM/vhdl_memory/mem(3) X"F0"
change /mp3_cpu/DRAM/vhdl_memory/mem(4) X"08"
change /mp3_cpu/DRAM/vhdl_memory/mem(5) X"6C"
change /mp3_cpu/DRAM/vhdl_memory/mem(6) X"A4"
change /mp3_cpu/DRAM/vhdl_memory/mem(7) X"1D"
change /mp3_cpu/DRAM/vhdl_memory/mem(8) X"08"
change /mp3_cpu/DRAM/vhdl_memory/mem(9) X"7C"
change /mp3_cpu/DRAM/vhdl_memory/mem(10) X"7F"
change /mp3_cpu/DRAM/vhdl_memory/mem(11) X"1B"
change /mp3_cpu/DRAM/vhdl_memory/mem(12) X"FA"
change /mp3_cpu/DRAM/vhdl_memory/mem(13) X"03"
change /mp3_cpu/DRAM/vhdl_memory/mem(14) X"FF"
change /mp3_cpu/DRAM/vhdl_memory/mem(15) X"0F"
change /mp3_cpu/DRAM/vhdl_memory/mem(16) X"12"
change /mp3_cpu/DRAM/vhdl_memory/mem(17) X"00"
change /mp3_cpu/DRAM/vhdl_memory/mem(18) X"21"
change /mp3_cpu/DRAM/vhdl_memory/mem(19) X"18"
change /mp3_cpu/DRAM/vhdl_memory/mem(20) X"C0"
change /mp3_cpu/DRAM/vhdl_memory/mem(21) X"C1"
change /mp3_cpu/DRAM/vhdl_memory/mem(22) X"21"
change /mp3_cpu/DRAM/vhdl_memory/mem(23) X"16"
change /mp3_cpu/DRAM/vhdl_memory/mem(24) X"C0"
change /mp3_cpu/DRAM/vhdl_memory/mem(25) X"C1"
change /mp3_cpu/DRAM/vhdl_memory/mem(26) X"21"
change /mp3_cpu/DRAM/vhdl_memory/mem(27) X"14"
change /mp3_cpu/DRAM/vhdl_memory/mem(28) X"C0"
change /mp3_cpu/DRAM/vhdl_memory/mem(29) X"C1"
change /mp3_cpu/DRAM/vhdl_memory/mem(30) X"21"
change /mp3_cpu/DRAM/vhdl_memory/mem(31) X"12"
change /mp3_cpu/DRAM/vhdl_memory/mem(32) X"C0"
change /mp3_cpu/DRAM/vhdl_memory/mem(33) X"C1"
run 5
echo "Done loading ../testcode/mp3/catchemall.asm program code."
