echo "--- Executing initialization force file for ../testcode/mp3/mp22-test-converted.asm ---"

echo "Resetting processor for 5 ns."
force /reset_l 0 @0
force /reset_l 1 @5

echo "Done initializing processor, loading ../testcode/mp3/mp22-test-converted.asm program code."
run 5
change /mp3_cpu/DRAM/vhdl_memory/mem(0) X"E5"
change /mp3_cpu/DRAM/vhdl_memory/mem(1) X"16"
change /mp3_cpu/DRAM/vhdl_memory/mem(2) X"0E"
change /mp3_cpu/DRAM/vhdl_memory/mem(3) X"6C"
change /mp3_cpu/DRAM/vhdl_memory/mem(4) X"00"
change /mp3_cpu/DRAM/vhdl_memory/mem(5) X"00"
change /mp3_cpu/DRAM/vhdl_memory/mem(6) X"00"
change /mp3_cpu/DRAM/vhdl_memory/mem(7) X"00"
change /mp3_cpu/DRAM/vhdl_memory/mem(8) X"00"
change /mp3_cpu/DRAM/vhdl_memory/mem(9) X"00"
change /mp3_cpu/DRAM/vhdl_memory/mem(10) X"00"
change /mp3_cpu/DRAM/vhdl_memory/mem(11) X"00"
change /mp3_cpu/DRAM/vhdl_memory/mem(12) X"00"
change /mp3_cpu/DRAM/vhdl_memory/mem(13) X"00"
change /mp3_cpu/DRAM/vhdl_memory/mem(14) X"0F"
change /mp3_cpu/DRAM/vhdl_memory/mem(15) X"64"
change /mp3_cpu/DRAM/vhdl_memory/mem(16) X"80"
change /mp3_cpu/DRAM/vhdl_memory/mem(17) X"6A"
change /mp3_cpu/DRAM/vhdl_memory/mem(18) X"46"
change /mp3_cpu/DRAM/vhdl_memory/mem(19) X"1D"
change /mp3_cpu/DRAM/vhdl_memory/mem(20) X"12"
change /mp3_cpu/DRAM/vhdl_memory/mem(21) X"66"
change /mp3_cpu/DRAM/vhdl_memory/mem(22) X"C0"
change /mp3_cpu/DRAM/vhdl_memory/mem(23) X"7C"
change /mp3_cpu/DRAM/vhdl_memory/mem(24) X"E0"
change /mp3_cpu/DRAM/vhdl_memory/mem(25) X"56"
change /mp3_cpu/DRAM/vhdl_memory/mem(26) X"FF"
change /mp3_cpu/DRAM/vhdl_memory/mem(27) X"0F"
change /mp3_cpu/DRAM/vhdl_memory/mem(28) X"78"
change /mp3_cpu/DRAM/vhdl_memory/mem(29) X"EA"
change /mp3_cpu/DRAM/vhdl_memory/mem(30) X"20"
change /mp3_cpu/DRAM/vhdl_memory/mem(31) X"00"
change /mp3_cpu/DRAM/vhdl_memory/mem(32) X"DD"
change /mp3_cpu/DRAM/vhdl_memory/mem(33) X"BA"
change /mp3_cpu/DRAM/vhdl_memory/mem(34) X"88"
change /mp3_cpu/DRAM/vhdl_memory/mem(35) X"88"
change /mp3_cpu/DRAM/vhdl_memory/mem(36) X"28"
change /mp3_cpu/DRAM/vhdl_memory/mem(37) X"00"
change /mp3_cpu/DRAM/vhdl_memory/mem(38) X"2A"
change /mp3_cpu/DRAM/vhdl_memory/mem(39) X"00"
run 5
echo "Done loading ../testcode/mp3/mp22-test-converted.asm program code."
