echo "--- Executing initialization force file for ../testcode/mp3/stldb.asm ---"

echo "Resetting processor for 5 ns."
force /reset_l 0 @0
force /reset_l 1 @5

echo "Done initializing processor, loading ../testcode/mp3/stldb.asm program code."
run 5
change /mp3_cpu/DRAM/vhdl_memory/mem(0) X"0F"
change /mp3_cpu/DRAM/vhdl_memory/mem(1) X"62"
change /mp3_cpu/DRAM/vhdl_memory/mem(2) X"21"
change /mp3_cpu/DRAM/vhdl_memory/mem(3) X"10"
change /mp3_cpu/DRAM/vhdl_memory/mem(4) X"1C"
change /mp3_cpu/DRAM/vhdl_memory/mem(5) X"24"
change /mp3_cpu/DRAM/vhdl_memory/mem(6) X"20"
change /mp3_cpu/DRAM/vhdl_memory/mem(7) X"50"
change /mp3_cpu/DRAM/vhdl_memory/mem(8) X"1C"
change /mp3_cpu/DRAM/vhdl_memory/mem(9) X"26"
change /mp3_cpu/DRAM/vhdl_memory/mem(10) X"A8"
change /mp3_cpu/DRAM/vhdl_memory/mem(11) X"D4"
change /mp3_cpu/DRAM/vhdl_memory/mem(12) X"83"
change /mp3_cpu/DRAM/vhdl_memory/mem(13) X"14"
change /mp3_cpu/DRAM/vhdl_memory/mem(14) X"11"
change /mp3_cpu/DRAM/vhdl_memory/mem(15) X"72"
change /mp3_cpu/DRAM/vhdl_memory/mem(16) X"09"
change /mp3_cpu/DRAM/vhdl_memory/mem(17) X"E6"
change /mp3_cpu/DRAM/vhdl_memory/mem(18) X"C0"
change /mp3_cpu/DRAM/vhdl_memory/mem(19) X"34"
change /mp3_cpu/DRAM/vhdl_memory/mem(20) X"98"
change /mp3_cpu/DRAM/vhdl_memory/mem(21) X"D4"
change /mp3_cpu/DRAM/vhdl_memory/mem(22) X"C1"
change /mp3_cpu/DRAM/vhdl_memory/mem(23) X"34"
change /mp3_cpu/DRAM/vhdl_memory/mem(24) X"C0"
change /mp3_cpu/DRAM/vhdl_memory/mem(25) X"60"
change /mp3_cpu/DRAM/vhdl_memory/mem(26) X"FF"
change /mp3_cpu/DRAM/vhdl_memory/mem(27) X"0F"
change /mp3_cpu/DRAM/vhdl_memory/mem(28) X"55"
change /mp3_cpu/DRAM/vhdl_memory/mem(29) X"A5"
change /mp3_cpu/DRAM/vhdl_memory/mem(30) X"DD"
change /mp3_cpu/DRAM/vhdl_memory/mem(31) X"BA"
change /mp3_cpu/DRAM/vhdl_memory/mem(32) X"88"
change /mp3_cpu/DRAM/vhdl_memory/mem(33) X"88"
run 5
echo "Done loading ../testcode/mp3/stldb.asm program code."
